extends CharacterBody2D

@export var speed = 200
var damage = 1

func _ready() -> void:
	var screen_size = get_viewport_rect().size
	GameManager.init_screen_size(screen_size.x, screen_size.y)

func _process(delta):
	velocity = Vector2.ZERO
	if Input.is_action_pressed("move_right"):
		velocity.x += 1
	if Input.is_action_pressed("move_left"):
		velocity.x -= 1
	if Input.is_action_pressed("move_down"):
		velocity.y += 1
	if Input.is_action_pressed("move_up"):
		velocity.y -= 1

	move_and_collide(speed * velocity * delta)
	#position += speed * velocity * delta
	position = GameManager.get_boundaried_position(position)
	
